### ISSUE TITLE
loadbalanced setup

### ISSUE THREAD

**Issue by sbagmeijer** [NUKIB/misp#27]
I am trying to setup your docker container on 2 different servers with a shared storage attached for the directories required.

I have some issue with when the database is created by the intial setup, and then when I start the second container on the other server that it breaks (i think) on the database creation script. Is there a way to say to not create the database if it exists?
```
root      900812  356782  0 13:01 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 50000 -container-ip 172.18.0.3 -container-port 50000
root      900824  356782  0 13:01 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 8080 -container-ip 172.18.0.3 -container-port 80
root      900839       1  0 13:01 ?        00:00:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 
root      900860  900839  0 13:01 ?        00:00:00 bash /usr/local/bin/docker-entrypoint.sh supervisord -c /etc/supervisord.conf
48        900933  900860  0 13:01 ?        00:00:00 python3 /usr/local/bin/misp_create_database.py XX.XX.XX.XX misp misp /var/www/MISP/INSTALL/MYSQL.sql
```

I see this in the processes and the container keeps restarting endless.

this is my docker file:
```
version: '3.3'

services:
  misp-modules:
    image: ghcr.io/nukib/misp-modules:latest
    restart: always
    container_name: misp-modules

  misp:
    image: ${MISP_IMAGE-ghcr.io/nukib/misp:latest}
    restart: always
    container_name: misp
    tmpfs:
      - /tmp
    volumes:
      - /mount/nfs/MISP/app/files/certs:/var/www/MISP/app/files/certs
      - /mount/nfs/MISP/app/attachments:/var/www/MISP/app/attachments
      - /mount/nfs/MISP/app/tmp/logs:/var/www/MISP/app/tmp/logs
      - /mount/nfs/MISP/.gnupg:/var/www/MISP/.gnupg
    environment:
      MYSQL_HOST: xx.xx.xx.xx
      MYSQL_LOGIN: misp
      MYSQL_PASSWORD: XXX
      MYSQL_DATABASE: misp
      REDIS_HOST: xx.xx.xx.xx
      REDIS_PASSWORD: "XXX"
      MISP_BASEURL: https://xx.xx.com
      MISP_UUID: XXX
      MISP_ORG: XXX
      MISP_MODULE_URL: http://misp-modules
      SMTP_HOST: XXX
      MISP_EMAIL: XXX@XXX.com
      SECURITY_SALT: XXX"
      ZEROMQ_ENABLED: "yes"
      SECURITY_CRYPTO_POLICY: FUTURE
      SECURITY_ENCRYPTION_KEY: "XXX"
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:50000:50000
 ```
 
 is there  anything special i need to do to make this work?
